<?php

return [
    'login'=>'site/login',
    ''=>'site/index',
    ''=>'site',
    'index' => 'site',
    
    'gaji' => 'gaji/simas-gaji-mstpegawai/index',
    'simpeg' => 'simpeg/eps-mastfip/index',
    'siasn' => 'siasn/siasn-data-utama/index',
    'sinkron' => 'siasn/tbl-data-update/index',
    'response-siasn' => 'siasn/siasn-ws/index',
    'asn' => 'integrasi/siasn-data-utama/cari',
    'asn-opd' => 'integrasi/siasn-data-utama/cari-opd',
    'data-asn' => 'integrasi/siasn-data-utama/index',
    'detail-asn' => 'integrasi/siasn-data-utama/view',
    'profil-asn' => 'integrasi/siasn-data-utama/profil',
    'cpns-pns-pppk' => 'integrasi/siasn-data-utama/cpns-pns-p3k',
    'siasn-get-data' => 'integrasi/siasn-get-data/index',
    'siasn-get-dok' => 'integrasi/siasn-get-data/get-dok',
    'siasn-show-dok' => 'integrasi/siasn-get-data/show-dok',
    'unor' => 'integrasi/siasn-ref-unor/index',
    'all-unor' => 'integrasi/siasn-ref-unor/all-unor',
    'download-unor' => 'integrasi/siasn-ref-unor/get-ref',
    'dokumen' => 'integrasi/ref-dokumen/index',
    'data-anomali' => 'integrasi/siasn-anomali/index',
   
    'data-profil' => 'integrasi/data-asn/profil',
    'data-cpns-pns' => 'integrasi/data-asn/cpns-pns',
    'data-pangkat' => 'integrasi/data-asn/gol',
    'data-jabatan' => 'integrasi/data-asn/jabatan',
    'data-skp22' => 'integrasi/data-asn/skp22',
    'data-skp' => 'integrasi/data-asn/skp',
    'data-pendidikan' => 'integrasi/data-asn/pendidikan',
    'data-diklat' => 'integrasi/data-asn/diklat',
    'data-rw-unor' => 'integrasi/data-asn/unor',
    'upload-dok-rw' => 'integrasi/siasn-post-data/upload-dok-rw',
    'upload-dok' => 'integrasi/siasn-post-data/upload-dok',
    'post-data' => 'integrasi/siasn-post-data/index',
    
    'setting-asn' => 'sitampan/preskin-asn/index',
    'setting-libur' => 'sitampan/preskin-libur/index',
    'setting-jenis-libur' => 'sitampan/preskin-libur-jenis/index',
    'setting-hari-kerja' => 'sitampan/preskin-hari-kerja/index',
    'setting-jam-kerja' => 'sitampan/preskin-jam-kerja/index',
    'setting-ket-presensi' => 'sitampan/preskin-pres-jenis/index',
    'setting-ket-absen' => 'sitampan/pres-ket-jenis/index',
    'setting-kelas-tpp' => 'sitampan/preskin-pagu-tpp/index',
    'setting-lokasi-presensi' => 'sitampan/fp-tb-alamat2/index',
    'setting-parameter' => 'sitampan/preskin-param/index',
    'presensi-jadwal' => 'sitampan/pres-harian/index',
    'presensi-hasil' => 'sitampan/pres-harian/hasil',
    'presensi-asn' => 'sitampan/pres-harian/presensi-asn',
    'keterangan-absen' => 'sitampan/pres-ket/index',
    'reset-apk' => 'sitampan/fp-tb-daftarfinger/index',
    'reset' => 'sitampan/kesra/reset',
    'tambah' => 'sitampan/kesra/tambah',    
    'data-kinerja' => 'sitampan/kesra/kinerja',
    'data-presensi' => 'sitampan/kesra/presensi-asn',
    'data-tpp' => 'sitampan/kesra/tpp',
    'asn-presensi' => 'sitampan/kesra/preskin-asn',  
    'kinerja-data' => 'sitampan/kin-harian/index',
    'tpp-pns' => 'sitampan/preskin-tpp-hitung/pns',
    'tpp-plt' => 'sitampan/preskin-tpp-hitung/tpp-plt',
    'tpp-penerima' => 'sitampan/preskin-tpp-hitung/penerima-tpp',
    'tpp-opd' => 'sitampan/preskin-tpp-hitung/opd',
    'tpp-cetak' => 'sitampan/preskin-tpp-hitung/cetak-form',
    'cetak-tpp' => 'sitampan/preskin-tpp-hitung/cetak-pdf',
    'anomali-unor' => 'integrasi/anomali/unor-non-aktif',
    'anomali-bup' => 'integrasi/anomali/bup-aktif',
    'anomali-skp' => 'integrasi/anomali/skp',
    'anomali-nik' => 'integrasi/anomali/nik',
    // 'anomali' => 'integrasi/anomali/',

    'dataasn' => 'integrasi/supervisi/cari',

    '<controller:\w+>/<action:\w+>'=>'<controller>/<action>',
    ['class' => 'app\config\UrlRule', 'connectionID' => 'db'],
];
